import type { TextfieldConfig } from '../types/merged'

export default {
  color: {
    bg: 'bg-gray-200 dark:bg-zinc-800',
    text: 'text-black dark:text-white',
    hint: 'text-gray-600 dark:text-gray-400',
    error: 'text-red-500 dark:text-red-500',
    label: 'text-black dark:text-white',
    labelFocus: 'peer-focus:text-primary-600',
    placeholderText: 'placeholder:text-gray-400 dark:placeholder:text-gray-600',
    icon: 'text-black dark:text-white',
    iconFocus: 'group-focus-within:text-primary-600',
    border: 'border-black dark:border-white',
    borderFocus: 'focus:border-primary-800 dark:focus:border-primary-800',
    borderError: 'border-red-500',
    borderFocusError: 'focus:border-red-500',
  },
  font: {
    label: 'text-sm',
    input: 'text-sm',
    placeholder: 'text-sm',
    hint: 'text-sm',
  },
  label: 'Label',
  autocomplete: 'on',
  prependIcon: false,
  appendIcon: false,
  clearable: false,
  disabled: false,
  loading: false,
  rounded: 'rounded-lg',
  outlined: 'border',
  filled: 'border-b-2',
  placeholder: ' ',
  hint: '',
  shadow: 'shadow-lg',
  type: 'text',
  transition: {
    duration: 'duration-300',
    ease: 'ease-in-out',
    placeholder: {
      duration: 'placeholder:duration-500',
      ease: 'placeholder:ease-in-out',
    },
  },
  width: 'w-full',
  rules: [],
} satisfies TextfieldConfig
