name: Release

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version-file: "./module/package.json"

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: 🟢 node
        uses: actions/setup-node@v3.6.0
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: 📦 install
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: npm install
        working-directory: ./module

      - name: 🌀 prepare
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: npm run dev:prepare
        working-directory: ./module

      - name: 🚀 publish
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: npm publish --access public
        working-directory: ./module
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
