name: Release

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version-file: "./module/package.json"

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - uses: actions/setup-node@v3
        working-directory: ./module
        with:
          node-version: 12
      - run: npm install
        working-directory: ./module
      - run: npm test
        working-directory: ./module
      - uses: JS-DevTools/npm-publish@v1
        working-directory: ./module
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./module/package.json"
          access: "public"
