on:
  push:
    branches:
      - main
jobs:
  changelog:
  runs-on: ubuntu-latest
    steps:
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version-file: "./module/package.json"
          
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Publish Release
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 12
        run: npm install
        run: npm test
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}